### ISSUE TITLE
身份证号码生成问题

### ISSUE THREAD

**Issue by fjnuwm** [tzattack/Idcard_random_generator#1]
你好，身份证号的生成少了地址码的模块
![1532918837 1](https://user-images.githubusercontent.com/31117662/43375174-03e4ba58-93e6-11e8-949e-e00849d7c458.jpg)

**Comment by tzattack** [comment]
sorry, the addr module is deleted unexpectedly, I have already upload it, you need to pull the project and try it out. If you need any help, you can contact me at ease. Please star this project to help me build more stuff. You are much appreciated.

**Comment by fjnuwm** [comment]
ok,thanks!
